const SUB_COMMAND_ADD = "add";
const SUB_COMMAND_LIST = "list";
const SUB_COMMAND_SHOW = "show";
const SUB_COMMAND_UPDATE = "update";
const SUB_COMMAND_DELETE = "delete";

const SUB_COMMANDS = new Set([
  SUB_COMMAND_ADD,
  SUB_COMMAND_LIST,
  SUB_COMMAND_SHOW,
  SUB_COMMAND_UPDATE,
  SUB_COMMAND_DELETE,
]);

const COMMAND_DESCRIPTIONS: Record<string, string> = {
  [SUB_COMMAND_ADD]: "Googleカレンダーに予定を追加します",
  [SUB_COMMAND_LIST]: "指定期間におけるGoogleカレンダーの予定を一覧表示します",
  [SUB_COMMAND_SHOW]: "指定した予定の詳細を表示します",
  [SUB_COMMAND_UPDATE]: "指定した予定を更新します",
  [SUB_COMMAND_DELETE]: "指定した予定を削除します",
};

export type SubCommandType =
  | typeof SUB_COMMAND_ADD
  | typeof SUB_COMMAND_LIST
  | typeof SUB_COMMAND_SHOW
  | typeof SUB_COMMAND_UPDATE
  | typeof SUB_COMMAND_DELETE;

const CUSTOM_ID_ADD = "add";
const CUSTOM_ID_SHOW = "show";
const CUSTOM_ID_UPDATE = "update";
const CUSTOM_ID_DELETE = "delete";

const CUSTOM_ID_ADD_INPUTS_TITLE = "add_inputs_title";
const CUSTOM_ID_ADD_INPUTS_START_AT = "add_inputs_start_at";
const CUSTOM_ID_ADD_INPUTS_END_AT = "add_inputs_end_at";
const CUSTOM_ID_ADD_INPUTS_DESCRIPTION = "add_inputs_description";
const CUSTOM_ID_ADD_INPUTS_REMIND_DAYS = "add_inputs_remind_days";
const CUSTOM_ID_ADD_INPUTS_ROLE_IDS = "add_inputs_role_ids";
const CUSTOM_ID_ADD_INPUTS_MEMBER_IDS = "add_inputs_member_ids";

const CUSTOM_IDS = new Set([
  CUSTOM_ID_ADD,
  CUSTOM_ID_SHOW,
  CUSTOM_ID_UPDATE,
  CUSTOM_ID_DELETE,
]);

const CUSTOM_ID_ADD_INPUTS = new Set([
  CUSTOM_ID_ADD_INPUTS_TITLE,
  CUSTOM_ID_ADD_INPUTS_START_AT,
  CUSTOM_ID_ADD_INPUTS_END_AT,
  CUSTOM_ID_ADD_INPUTS_DESCRIPTION,
  CUSTOM_ID_ADD_INPUTS_REMIND_DAYS,
  CUSTOM_ID_ADD_INPUTS_ROLE_IDS,
  CUSTOM_ID_ADD_INPUTS_MEMBER_IDS,
]);

const CUSTOM_ID_ADD_MODAL = "add_modal";

export {
  COMMAND_DESCRIPTIONS,
  SUB_COMMAND_ADD,
  SUB_COMMAND_LIST,
  SUB_COMMAND_SHOW,
  SUB_COMMAND_UPDATE,
  SUB_COMMAND_DELETE,
  SUB_COMMANDS,
  CUSTOM_ID_ADD,
  CUSTOM_ID_SHOW,
  CUSTOM_ID_UPDATE,
  CUSTOM_ID_DELETE,
  CUSTOM_IDS,
  CUSTOM_ID_ADD_INPUTS_TITLE,
  CUSTOM_ID_ADD_INPUTS_START_AT,
  CUSTOM_ID_ADD_INPUTS_END_AT,
  CUSTOM_ID_ADD_INPUTS_DESCRIPTION,
  CUSTOM_ID_ADD_INPUTS_REMIND_DAYS,
  CUSTOM_ID_ADD_INPUTS_ROLE_IDS,
  CUSTOM_ID_ADD_INPUTS_MEMBER_IDS,
  CUSTOM_ID_ADD_INPUTS,
  CUSTOM_ID_ADD_MODAL,
};
