const MONTH_CHOICES = [
	{ name: "1月", value: 1 },
	{ name: "2月", value: 2 },
	{ name: "3月", value: 3 },
	{ name: "4月", value: 4 },
	{ name: "5月", value: 5 },
	{ name: "6月", value: 6 },
	{ name: "7月", value: 7 },
	{ name: "8月", value: 8 },
	{ name: "9月", value: 9 },
	{ name: "10月", value: 10 },
	{ name: "11月", value: 11 },
	{ name: "12月", value: 12 },
];

const DAY_CHOICES = [
	{ name: "1日", value: 1 },
	{ name: "2日", value: 2 },
	{ name: "3日", value: 3 },
	{ name: "4日", value: 4 },
	{ name: "5日", value: 5 },
	{ name: "6日", value: 6 },
	{ name: "7日", value: 7 },
	{ name: "8日", value: 8 },
	{ name: "9日", value: 9 },
	{ name: "10日", value: 10 },
	{ name: "11日", value: 11 },
	{ name: "12日", value: 12 },
	{ name: "13日", value: 13 },
	{ name: "14日", value: 14 },
	{ name: "15日", value: 15 },
	{ name: "16日", value: 16 },
	{ name: "17日", value: 17 },
	{ name: "18日", value: 18 },
	{ name: "19日", value: 19 },
	{ name: "20日", value: 20 },
	{ name: "21日", value: 21 },
	{ name: "22日", value: 22 },
	{ name: "23日", value: 23 },
	{ name: "24日", value: 24 },
	{ name: "25日", value: 25 },
	{ name: "26日", value: 26 },
	{ name: "27日", value: 27 },
	{ name: "28日", value: 28 },
	{ name: "29日", value: 29 },
	{ name: "30日", value: 30 },
	{ name: "31日", value: 31 },
];

const HOUR_CHOICES = [
	{ name: "00", value: "00" },
	{ name: "01", value: "01" },
	{ name: "02", value: "02" },
	{ name: "03", value: "03" },
	{ name: "04", value: "04" },
	{ name: "05", value: "05" },
	{ name: "06", value: "06" },
	{ name: "07", value: "07" },
	{ name: "08", value: "08" },
	{ name: "09", value: "09" },
	{ name: "10", value: "10" },
	{ name: "11", value: "11" },
	{ name: "12", value: "12" },
	{ name: "13", value: "13" },
	{ name: "14", value: "14" },
	{ name: "15", value: "15" },
	{ name: "16", value: "16" },
	{ name: "17", value: "17" },
	{ name: "18", value: "18" },
	{ name: "19", value: "19" },
	{ name: "20", value: "20" },
	{ name: "21", value: "21" },
	{ name: "22", value: "22" },
	{ name: "23", value: "23" },
];

const MINUTE_CHOICES = [
	{ name: "00", value: "00" },
	{ name: "01", value: "01" },
	{ name: "02", value: "02" },
	{ name: "03", value: "03" },
	{ name: "04", value: "04" },
	{ name: "05", value: "05" },
	{ name: "06", value: "06" },
	{ name: "07", value: "07" },
	{ name: "08", value: "08" },
	{ name: "09", value: "09" },
	{ name: "10", value: "10" },
	{ name: "11", value: "11" },
	{ name: "12", value: "12" },
	{ name: "13", value: "13" },
	{ name: "14", value: "14" },
	{ name: "15", value: "15" },
	{ name: "16", value: "16" },
	{ name: "17", value: "17" },
	{ name: "18", value: "18" },
	{ name: "19", value: "19" },
	{ name: "20", value: "20" },
	{ name: "21", value: "21" },
	{ name: "22", value: "22" },
	{ name: "23", value: "23" },
	{ name: "24", value: "24" },
	{ name: "25", value: "25" },
	{ name: "26", value: "26" },
	{ name: "27", value: "27" },
	{ name: "28", value: "28" },
	{ name: "29", value: "29" },
	{ name: "30", value: "30" },
	{ name: "31", value: "31" },
	{ name: "32", value: "32" },
	{ name: "33", value: "33" },
	{ name: "34", value: "34" },
	{ name: "35", value: "35" },
	{ name: "36", value: "36" },
	{ name: "37", value: "37" },
	{ name: "38", value: "38" },
	{ name: "39", value: "39" },
	{ name: "40", value: "40" },
	{ name: "41", value: "41" },
	{ name: "42", value: "42" },
	{ name: "43", value: "43" },
	{ name: "44", value: "44" },
	{ name: "45", value: "45" },
	{ name: "46", value: "46" },
	{ name: "47", value: "47" },
	{ name: "48", value: "48" },
	{ name: "49", value: "49" },
	{ name: "50", value: "50" },
	{ name: "51", value: "51" },
	{ name: "52", value: "52" },
	{ name: "53", value: "53" },
	{ name: "54", value: "54" },
	{ name: "55", value: "55" },
	{ name: "56", value: "56" },
	{ name: "57", value: "57" },
	{ name: "58", value: "58" },
	{ name: "59", value: "59" },
];

export const ADD_COMMAND = "add";
export const LIST_COMMAND = "list";
export const UPDATE_COMMAND = "update";
export const DELETE_COMMAND = "delete";

export const COMMANDS = {
	ADD_COMMAND: {
		name: ADD_COMMAND,
		description: "Google Calendarに予定を追加します",
		options: [
			{
				name: "title",
				description: "予定のタイトル",
				type: 3,
				required: true,
			},
			{
				name: "start_year",
				description: "予定の開始年",
				type: 4,
				required: true,
			},
			{
				name: "start_month",
				description: "予定の開始月",
				type: 4,
				required: true,
				choices: MONTH_CHOICES,
			},
			{
				name: "start_day",
				description: "予定の開始日",
				type: 4,
				required: true,
				choices: DAY_CHOICES,
			},
			{
				name: "start_hour",
				description: "予定の開始時刻",
				type: 3,
				required: true,
				choices: HOUR_CHOICES,
			},
			{
				name: "start_minute",
				description: "予定の開始分",
				type: 3,
				required: true,
				choices: MINUTE_CHOICES,
			},
			{
				name: "end_year",
				description: "予定の終了年",
				type: 4,
				required: true,
			},
			{
				name: "end_month",
				description: "予定の終了月",
				type: 4,
				required: true,
				choices: MONTH_CHOICES,
			},
			{
				name: "end_day",
				description: "予定の終了日",
				type: 4,
				required: true,
				choices: DAY_CHOICES,
			},
			{
				name: "end_hour",
				description: "予定の終了時刻",
				type: 3,
				required: true,
				choices: HOUR_CHOICES,
			},
			{
				name: "description",
				description: "予定の詳細",
				type: 3,
				required: false,
			},
		],
	},
	LIST_COMMAND: {
		name: LIST_COMMAND,
		description: "Google Calendarの予定を一覧表示します",
		options: [
			{
				name: "year",
				description: "予定の年",
				type: 4,
				required: true,
			},
			{
				name: "month",
				description: "予定の月",
				type: 4,
				required: true,
				choices: MONTH_CHOICES,
			},
			{
				name: "day",
				description: "予定の日",
				type: 4,
				required: true,
				choices: DAY_CHOICES,
			},
		],
	},
	UPDATE_COMMAND: {
		name: UPDATE_COMMAND,
		description: "Google Calendarの予定を更新します",
		options: [
			{
				name: "event_id",
				description: "更新する予定のID",
				type: 3,
				required: true,
			},
			{
				name: "title",
				description: "予定のタイトル",
				type: 3,
				required: false,
			},
			{
				name: "start_year",
				description: "予定の開始年",
				type: 4,
				required: false,
			},
			{
				name: "start_month",
				description: "予定の開始月",
				type: 4,
				required: false,
				choices: MONTH_CHOICES,
			},
			{
				name: "start_day",
				description: "予定の開始日",
				type: 4,
				required: false,
				choices: DAY_CHOICES,
			},
			{
				name: "start_hour",
				description: "予定の開始時刻",
				type: 3,
				required: false,
				choices: HOUR_CHOICES,
			},
			{
				name: "start_minute",
				description: "予定の開始分",
				type: 3,
				required: false,
				choices: MINUTE_CHOICES,
			},
			{
				name: "end_year",
				description: "予定の終了年",
				type: 4,
				required: false,
			},
			{
				name: "end_month",
				description: "予定の終了月",
				type: 4,
				required: false,
				choices: MONTH_CHOICES,
			},
			{
				name: "end_day",
				description: "予定の終了日",
				type: 4,
				required: false,
				choices: DAY_CHOICES,
			},
			{
				name: "end_hour",
				description: "予定の終了時刻",
				type: 3,
				required: false,
				choices: HOUR_CHOICES,
			},
			{
				name: "description",
				description: "予定の詳細",
				type: 3,
				required: false,
			},
		],
	},
	DELETE_COMMAND: {
		name: DELETE_COMMAND,
		description: "Google Calendarの予定を削除します",
		options: [
			{
				name: "event_id",
				description: "削除する予定のID",
				type: 3,
				required: true,
			},
		],
	},
};
